# **NumPy**

**NumPy (Numerical Pythons)** is an open-source Python library for scientific computing. 

It provides support for efficient, large, multi-dimensional array objects (called ndarray) and a vast collection of high-level mathematical functions to operate on these arrays.

**cmd:**
```bash
pip install numpy
```
**Also:**
```bash
pip install pandas
pip install matplotlib
```

In [41]:
import numpy as np
li = [1, 2, 3]
print(li)
arr = np.array(li)
print(arr)
print(type(arr))

[1, 2, 3]
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

print(np.zeros(3))
print(np.ones(3))
print(np.eye(3))
print(np.random.rand(5))
# print(np.random.rand(3))
print(np.random.randint(10, 30))
# print(np.random.randint(1, 3))
# arr = np.random.rand(3)
# print(arr)
# print(type(arr[0]))

[0. 0. 0.]
[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.97307156 0.33290192 0.73977744 0.64209888 0.57981978]
28
[0.220852   0.71389041 0.13029972]
<class 'numpy.float64'>


## **Array Attributes**

|Attributes|	Description|
|---|---|
|ndim	|returns number of dimension of the array|
|size	|returns number of elements in the array|
|dtype	|returns data type of elements in the array|
|shape	|returns the size of the array in each dimension.|
|itemsize	|returns the size (in bytes) of each elements in the array|
|data	|returns the buffer containing actual elements of the array in memory|


In [84]:

import numpy as np

arr = np.array([1, 2, 3])
print(arr.shape)

arr = np.array([[1], [2]])
print(arr.shape)

(3,)
(2, 1)


In [88]:
import numpy as np

def display(arr: np.array):
    print(arr, f"N Dimension: {arr.ndim}", f"Size: {arr.size}", f"dType: {arr.dtype}", f"Item Size: {arr.itemsize}", f"Shape: {arr.shape}", f"Data: {arr.data}", '\n', sep='\n')
    
arr = np.array([1, 2, 3])   # One Dimensional
display(arr)

arr = np.array([[1, 2, 3]]) # Two Dimensional
display(arr)

arr = np.array([[1, 2, 3], [4, 5, 6]])   # Two Dimensional
display(arr)

arr = np.array([[[1], [2]]])   # Three Dimensional
display(arr)

[1 2 3]
N Dimension: 1
Size: 3
dType: int64
Item Size: 8
Shape: (3,)
Data: <memory at 0x10615fd00>


[[1 2 3]]
N Dimension: 2
Size: 3
dType: int64
Item Size: 8
Shape: (1, 3)
Data: <memory at 0x1061ebed0>


[[1 2 3]
 [4 5 6]]
N Dimension: 2
Size: 6
dType: int64
Item Size: 8
Shape: (2, 3)
Data: <memory at 0x1061ebed0>


[[[1]
  [2]]]
N Dimension: 3
Size: 2
dType: int64
Item Size: 8
Shape: (1, 2, 1)
Data: <memory at 0x10589bc40>




## **Array Indexing, Range, Slicing & Iteration**

### **Indexing**

#### **1D**

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr[0])
print(arr[1])
print(arr[2])


1
2
3


#### **2D**

In [46]:
import numpy as np

arr = np.array([[1],[2]])
print(arr[0][0])

1


### **Range**

In [21]:
import numpy as np

arr = np.array(range(1, 5))
print(arr)

[1 2 3 4]


In [ ]:
import numpy as np

arr = np.array()

In [ ]:
import numpy as np

arr = np.array(range(1, 11))
print(arr)
# print(arr[5:])
# print(arr[1:5])
# print(arr[1:5:2])
# print(arr[1::2])
# print(arr[::-1])

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


#### **Iteration**

In [47]:
import numpy as np

arr = np.array([50, 9, 4, 44])

for i in arr:
    print(i)

50
9
4
44


In [99]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
# print(arr)

for row in arr:
    for data in row:
        print(data, end='\t')
    print()

1	2	
3	4	


In [50]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

for i in arr:
    for j in i:
        print(j, end=' ')
    print()

1 2 
3 4 


In [54]:
import numpy as np

arr = np.array([10, 20, -3])

for index, value in np.ndenumerate(arr):
    print(f"{index}: {value}")


(0,): 10
(1,): 20
(2,): -3


## **Copying**

In [2]:
import numpy as np

a = np.array([1, 2, 3])
b = a.view()
print(a, b)
b[0] = 200
print(a, b)

[1 2 3] [1 2 3]
[200   2   3] [200   2   3]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = a.copy()
print(a, b)
b[0] = 200
print(a, b)

[1 2 3] [1 2 3]
[1 2 3] [200   2   3]


In [7]:
import numpy as np

a = np.array([[1], [2]])
b = a.copy()

print(a, b, sep='\n')
print('\n')

b[0][0] = 200

print(a, b, sep='\n')

[[1]
 [2]]
[[1]
 [2]]


[[1]
 [2]]
[[200]
 [  2]]


## **Sorting & Searching**

In [20]:
import numpy as np

arr = np.array([1, 1, 2, -5, 9, 6])
arr.sort()
print(arr)

[-5  1  1  2  6  9]


In [57]:
import numpy as np

arr = np.array([1, 2, 3])
print(np.where(arr == 2))
print(np.where(arr > 2))

(array([1]),)
(array([2]),)


### **searchsorted()**

If you have a sorted array and want to find the index where a specific value would be inserted to maintain the sort order (binary search), use numpy.searchsorted(). This is much faster than a linear search for large arrays.

In [14]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])
print(arr)
print(arr.searchsorted(2))

# print(arr.searchsorted(-2))


# arr = np.insert(arr, 2, 7)
# print(arr)


[0 1 2 3 4 5]
2


## **List vs. NumPy Arrays**



In [31]:
li = [1, 1, 1]

print(li)
print(li[0])
print(type(li[0]))

[1, 1, 1]
1
<class 'int'>


In [30]:
import numpy as np

arr = np.ones(3)

print(arr)
print(arr[0])
print(type(arr[0]))

[1. 1. 1.]
1.0
<class 'numpy.float64'>


In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(a)
print(type(a))

a = np.array([[1, 2], [3]])

In [40]:
import numpy as np

a = np.array([1, 2, 3])
print(a)
print(a.sum())
print(a.prod())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.var())

[1 2 3]
6
6
1
3
2.0
0.816496580927726
0.6666666666666666


## **Matrix Multiplication**

In [45]:
import numpy as np

a = np.array([[1, 2]])
b = np.array([[1], [2]])

print(a.__matmul__(b))

[[5]]


In [8]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])
print(a.__matmul__(b))

[[3 3]
 [7 7]]


#### **Task**

Write a code to display mean, variance, and standard deviation of the values of a .csv file.

In [ ]:
import numpy as np

data = []

with open("assets/data.csv", "r") as f:
    for line in f:
        values = line.strip().split(",")
        for v in values:
            data.append(float(v))

arr = np.array(data)

print("Mean:", np.mean(arr))
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))

Mean: 35.0
Variance: 291.6666666666667
Standard Deviation: 17.07825127659933


In [ ]:
import csv
import numpy as np

data = []

with open("assets/data.csv", "r") as f:
    reader = csv.reader(f)

    for row in reader:
        for value in row:
            data.append(float(value))

arr = np.array(data)

print("Mean:", np.mean(arr))
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))

Mean: 35.0
Variance: 291.6666666666667
Standard Deviation: 17.07825127659933


## **Array Broadcasting**

Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different shapes without reshaping them. It automatically adjusts the smaller array to match the larger array's shape by replicating its values along the necessary dimensions. This makes element-wise operations more efficient by reducing memory usage and eliminating the need for loops.

When comparing shapes:

> Start from the rightmost dimension and move left.

Two dimensions are compatible if:

1. They are equal, OR
2. One of them is 1

In [8]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2]])

print(a, b, sep='\n')

print(a+b)

[[1 2]
 [3 4]]
[[1 2]]
[[2 4]
 [4 6]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = 1
print(a+b)

[[2 3 4]]


In [16]:
import numpy as np

a = np.array([[1, 2, 3]])
b = np.array([[1]])

print(a + b)


li_a = [[1, 2, 3]]
li_b = [[1]]
print(li_a + li_b)

[[2 3 4]]
[[1, 2, 3], [1]]


In [ ]:
import numpy as np

a = np.array([
    [1, 2, 3]
    ])
print(a)
print(a.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [26]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

b = np.array([
    [1, 3, 5]
])

c = np.array([
    [1],
    [3],
    [5]
])

print(a)
# print(b.T)
print(a+b)
print(a+c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  5  8]
 [ 5  8 11]
 [ 8 11 14]]
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [12]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [1, 2]])
print(a*b)
print()
print(a.__matmul__(b))

[[1 4]
 [3 8]]

[[ 3  6]
 [ 7 14]]


In [14]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2]])

print(a*b)
# print(a.__matmul__(b))

[[1 4]
 [3 8]]


In [3]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
x = 10
print(a + x)

[[11 12 13]
 [14 15 16]]


In [4]:
import numpy as np

a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7, 9, 11]])
res = a + b
print(res)

[[ 3  7 11]
 [ 9 13 17]]


In [5]:
import numpy as np
m = np.array([[1, 2], [3, 4]])
v = np.array([10, 20])
res = m * v
print(res)

[[10 40]
 [30 80]]
